version: '3.7'

services:
  busybox:
    image: busybox
    volumes: 
      - ./letsencrypt:/etc/letsencrypt
    command: /bin/sh -c "echo '*.$DOMAIN autorestart-containers=sish' > /etc/letsencrypt/domains.conf"
  letsencrypt:
    image: adferrand/letsencrypt-dns:latest
    container_name: letsencrypt-dns
    depends_on: 
      - busybox
    environment:
      - VERSION=latest
      - LETSENCRYPT_USER_MAIL
      - LEXICON_PROVIDER
      - LEXICON_PROVIDER_OPTIONS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/etc/letsencrypt
    restart: always
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    depends_on: 
      - letsencrypt
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
    command: |
      -sish.addr=:22
      -sish.https=:443
      -sish.http=:80
      -sish.httpsenabled=true
      -sish.httpspems=/etc/letsencrypt/live/$DOMAIN
      -sish.keysdir=/pubkeys
      -sish.pkloc=/keys/ssh_key
      -sish.bindrandom=false
      -sish.domain=$DOMAIN
      -sish.forcerandomsubdomain=false
    network_mode: host
    restart: always
